server:
  additionalApplications:
  - name: app-of-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/burnoutband/declarative-argocd.git
      targetRevision: HEAD
      path: getting-started/argocd
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      #automated:
      #  selfHeal: true
      #  prune: true
